"server only";

import { PinataSDK } from "pinata-web3";

export const pinata = new PinataSDK({
  pinataJwt:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI5ZjBjMjhiZS02ZjJkLTRiZDMtYTAyNS0wNzFjNzMyOTdiZTIiLCJlbWFpbCI6ImtpeXlha2ViZXJlQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiIxNTQ5OWNiM2YwZWU3NDA0NDViMCIsInNjb3BlZEtleVNlY3JldCI6IjU0MzYwYzg1ZDQ4MzhhMjE3ZTVkODNhNzhiOWU1ZDVjY2I1ZDJlM2MyZDFjZWI3OWRhN2ZhZTMxZTZlMGRlZjYiLCJleHAiOjE3NzA4MjUwMjl9.87UTTYL0dlA94ySGyuEzeFnYpOiFsvA3kOrpLsijkCw",
  pinataGateway: `emerald-adverse-shrew-513.mypinata.cloud`,
});
